-- copy and paste
-- if vim.g.neovide then
--   -- vim.keymap.set("n", "<D-s>", ":w<CR>") -- Save
--   vim.keymap.set("v", "<c-c>", '"+y') -- Copy
--   vim.keymap.set("n", "<c-v>", '"+P') -- Paste normal mode
--   vim.keymap.set("v", "<c-v>", '"+P') -- Paste visual mode
--   vim.keymap.set("c", "<c-v>", "<C-R>+") -- Paste command mode
--   vim.keymap.set("i", "<c-v>", '<ESC>l"+Pli') -- Paste insert mode
-- end
--
-- -- Allow clipboard copy paste in neovim
-- -- vim.api.nvim_set_keymap("", "<c-v>", "+p<CR>", { noremap = true, silent = true })
-- -- vim.api.nvim_set_keymap("!", "<c-v>", "<C-R>+", { noremap = true, silent = true })
-- -- vim.api.nvim_set_keymap("t", "<c-v>", "<C-R>+", { noremap = true, silent = true })
-- -- vim.api.nvim_set_keymap("v", "<c-v>", "<C-R>+", { noremap = true, silent = true })
--
-- -- Dynamically change scale
-- vim.g.neovide_scale_factor = 1.0
-- local change_scale_factor = function(delta)
--   vim.g.neovide_scale_factor = vim.g.neovide_scale_factor * delta
-- end
-- vim.keymap.set("n", "<C-=>", function()
--   change_scale_factor(1.25)
-- end)
-- vim.keymap.set("n", "<C-->", function()
--   change_scale_factor(1 / 1.25)
-- end)
--
return {}
